services:
  # Service 1: The Database
  weather-db:
    image: postgres:15
    container_name: weather_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: WeatherDb
    ports:
      - "5432:5432" # Allows you to connect via Rider/pgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: The Backend API
  weather-api:
    build:
      context: ./WeatherApp
      dockerfile: Dockerfile
    container_name: weather_api
    ports:
      - "5160:8080" # Maps localhost:5160 (Laptop) -> 8080 (Container)
    environment:
      # Magic: "weather-db" is the hostname of the database container!
      ConnectionStrings__DefaultConnection: "Host=weather-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ASPNETCORE_URLS: "http://+:8080"
      # Pass the API key securely (or use secrets in real prod)
      OpenWeather__ApiKey: ${OPENWEATHER_API_KEY}
    depends_on:
      - weather-db

  # Service 3: The Frontend Website
  weather-web:
    build:
      context: ./weather-dash
      dockerfile: Dockerfile
    container_name: weather_web
    ports:
      - "5173:80" # Maps localhost:5173 (Laptop) -> 80 (Container)
    depends_on:
      - weather-api

volumes:
  postgres_data: # Persist DB data even if you restart Docker