services:
  # Service 1: The Database
  weather-db:
    image: postgres:15
    container_name: weather_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Allows you to connect via Rider/pgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: The Backend API
  weather-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather_api
    ports:
      - "5160:8080" # Maps localhost:5160 (Laptop) -> 8080 (Container)
    environment:
      # Database connection (Points to the 'db' container, not localhost)
      - ConnectionStrings__DefaultConnection=Host=weather_db;Port=5432;Database=WeatherDb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      
      # Security & APIs (Mapped from .env)
      - Jwt__Key=${JWT_KEY}
      - OpenWeather__ApiKey=${OPENWEATHER_API_KEY}
      
      # Email
      - Email__Username=${EMAIL_USERNAME}
      - Email__Password=${EMAIL_PASSWORD}
      
      # AI Keys
      - AI__GroqKey=${AI_GROQ_KEY}
      - AI__GeminiKey=${AI_GEMINI_KEY}
      - AI__CerebrasKey=${AI_CEREBRAS_KEY}
    dns:
      - 8.8.8.8
      - 8.8.4.4


    depends_on:
      - weather-db

  # Service 3: The Frontend Website
  weather-web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: weather_web
    ports:
      - "5173:80" # Maps localhost:5173 (Laptop) -> 80 (Container)
    depends_on:
      - weather-api

volumes:
  postgres_data: # Persist DB data even if you restart Docker